# Generated by Django 5.2.3 on 2025-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('duration_min', models.IntegerField()),
                ('classification', models.CharField(max_length=5)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField(verbose_name='release date')),
                ('poster_url', models.URLField()),
                ('released', models.BooleanField(default=False)),
            ],
        ),
    ]
