# Generated by Django 5.2.3 on 2025-06-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_critic_delete_movie_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
