# Generated by Django 5.2.3 on 2025-06-27 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critic',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
