# Generated by Django 5.2.3 on 2025-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_critic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='critic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='critic',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
