# Generated by Django 5.2.3 on 2025-06-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_critic_likes_critic_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='critic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.category'),
        ),
    ]
